name: Build - NortonsoftHealth API

on:
  pull_request:
    branches: [ main ]

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - name: Chechout code
      uses: actions/checkout@v4 
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/NortonsoftHealth.Api/NortonsoftHealth.Api.sln

    - name: Build this API
      run: dotnet build src/NortonsoftHealth.Api/NortonsoftHealth.Api.sln --no-restore --configuration Release

    - name: Publish
      run: dotnet publish src/NortonsoftHealth.Api/NortonsoftHealth.Api.csproj --no-restore --no-build --configuration Release -o ./publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nortonsofthealth-api
        path: ./publish  