name: Build - NortonsoftHealth API

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]  
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/NortonsoftHealth.Api/NortonsoftHealth.Api.sln

    - name: Build this API
      run: dotnet build src/NortonsoftHealth.Api/NortonsoftHealth.Api.sln --no-restore --configuration Release

    - name: Publish
      run: dotnet publish src/NortonsoftHealth.Api/NortonsoftHealth.Api.csproj --no-restore --no-build --configuration Release -o ./publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nortonsofthealth-api
        path: ./publish  

  deploy:
    needs: build

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: nortonsofthealth-api      
        path: ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3 
      with:
        app-name: nortonsofthealth-api-dev
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish   