name: HelixCare CI Build

on:
  push:
    branches: [ main, feature/* ]
  
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - name: Chechout code
      uses: actions/checkout@v4 
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore HelixCare.Api/HelixCare.Api.sln

    - name: Build
      run: dotnet build HelixCare.Api/HelixCare.Api.sln --no-restore --configuration Release